import Head from 'next/head'
import styles from 'styles/Home.module.css'
import { Footer } from 'components/Footer'
import { Main } from 'components/Main'
import { Header } from 'components/Header'
import { useCallback } from 'react'
import Link from 'next/link';

export default function Home() {
  const foo = 1

  const handleClick = useCallback((e) => {
    console.log(e.target.href);
    e.preventDefault();
    alert(foo);
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Index Page</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      
      <Header />
      <Link href="/about">
        <a onClick={handleClick}>button</a>
      </Link>
      <Main page="index" />
      <Footer />
    </div>
  )
}





