import Head from 'next/head'
import styles from 'styles/Home.module.css'
import { Footer } from 'components/Footer'
import { Main } from 'components/Main'
import { Header } from 'components/Header'
import { useCallback, useEffect, useState } from 'react'
import Link from 'next/link';

export default function Home() {
  const [count, setCount] = useState(1)

  // let foo = 1

  const handleClick = (e) => {
    setCount((count) => count + 1)
    setCount((count) => count + 1)

    // foo = foo + 1;
  };

  useEffect(() => {
    // マウント時の処理
    // console.log("マウント時の処理")
    document.body.style.backgroundColor = "lightblue";

    // アンマウント時の処理
    return ( ) => {
      // console.log("アンマウント時の処理")
      document.body.style.backgroundColor = "";
    };
  },[]);

  console.log(count)

  return (
    <div className={styles.container}>
      <Head>
        <title>Index Page</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      
      <Header />
        <h1>{count}</h1>
        <button onClick={handleClick}>button</button>
      <Main page="index" />
      <Footer />
    </div>
  )
}





